#!/usr/bin/bash
# parse the converted csv files generated by scrape.sh
# depends on gnu or bsd grep and r

# config
output_csv=average_monthly_costs_cents-per-kWh.csv
month_csv="MONTH,NUMBER
January,1
February,2
March,3
April,4
May,5
June,6
July,7
August,8
September,9
October,10
November,11
December,12"

# setup
mkdir -p graphs

# usage: extract_column csv_file column_number
function extract_column() {
    grep "^Massachusetts" $1 | cut -d "," -f $2
}

# parse csv files to generate csv of all data. using column 4, commercial costs
#echo "YEAR,MONTH,AVERAGE RESIDENTIAL COST (cents/kWh),AVERAGE COMMERCIAL COST (cents/kWh),AVERAGE INDUSTRIAL COST (cents/kWh)" > $output_csv
echo "MONTHS SINCE JANUARY 2010,AVERAGE RESIDENTIAL COST (cents/kWh),AVERAGE COMMERCIAL COST (cents/kWh),AVERAGE INDUSTRIAL COST (cents/kWh)" > $output_csv
for csv in converted/*; do
    # $date_info: "State, [Month] YYYY and YYYY"
    date_info=$(grep -oE "State.*[0-9]+ and [0-9]+" "$csv")

    year=$(cut -d " " -f 3 <<< "$date_info")
    month=$(cut -d " " -f 2 <<< "$date_info")
    #echo "$year,$month,$(extract_column $csv 2),$(extract_column $csv 4),$(extract_column $csv 6)" | tee -a $output_csv

    month_number=$(grep $month <<< "$month_csv" | cut -d "," -f 2)
    months_since_january_2010=$[$month_number - 1 + (($year - 2010) * 12)]
    echo "$months_since_january_2010,$(extract_column $csv 2),$(extract_column $csv 4),$(extract_column $csv 6)" | tee -a $output_csv

done

Rscript gengraphs.r